[project]
name = 'Blockchain-Based-Specialized-Medical-Equipment-Tracking'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.calibration-tracking]
path = 'contracts/calibration-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.compliance-verification]
path = 'contracts/compliance-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.usage-logging]
path = 'contracts/usage-logging.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
